<?php


namespace panthsoni\tengxun\common;


class SingleValidate extends CommonValidate
{
    protected $rule = [
        'appid|appid' => 'length:0,50',
        'secret|secret' => 'length:0,50',
        'js_code|js_code'=>'length:0,50',
        'access_token|access_token' => 'length:0,255',
        'openid|openid'=>'length:0,50',
        'begin_date|begin_date'=>'dateFormat:Ymd',
        'end_date|begin_date'=>'dateFormat:Ymd',
        'touser|touser'=>'length:255',
        'msgtype|msgtype'=>'in:text,image,link,miniprogrampage',
        'text|text'=>'array',
        'image|image'=>'array',
        'link|link'=>'array',
        'miniprogrampage|miniprogrampage'=>'array',
        'command|command'=>'in:Typing,CancelTyping',
        'type|type'=>'in:image',
        'mp_template_msg|mp_template_msg'=>'array',
        'timestamp|timestamp'=>'length:0,100',
        'nonce|nonce'=>'length:0,100',
        'echostr|echostr'=>'length:0,100',
        'token|token'=>'length:0,100',
        'encoding_aes_key|encoding_aes_key'=>'length:0,100',
        'msg_signature|msg_signature'=>'length:0,100',
        'corpid|corpid'=>'length:0,50',
        'corpsecret|corpsecret'=>'length:0,50',
        'msg_type|msg_type'=>'in:text,voice,video,music,news,image,transfer_customer_service',
        'to_user_name|to_user_name'=>'length:0,50',
        'from_user_name|from_user_name'=>'length:0,50',
        'content|content'=>'length:0,255',
        'media_id|media_id'=>'length:0,50',
        'title|title'=>'length:0,50',
        'description|description'=>'length:0,255',
        'music_url|music_url'=>'length:0,255',
        'hq_music_url|hq_music_url'=>'length:0,255',
        'article_counts|article_counts'=>'between:1,8',
        'pic_url|pic_url'=>'length:0,255',
        'url|url'=>'length:0,255',
        'article_content|article_content'=>'array',
        'expire_seconds|expire_seconds'=>'number',
        'action_info|action_info'=>'array',
        'id|ID'=>'number',
        'name|name'=>'length:0,32',
        'name_en|name_en'=>'length:0,32',
        'parentid|parentid'=>'number',
        'order|order'=>'number',
        'button|button' => 'length:0,100',
        'industry_id1|industry_id1' => 'number',
        'industry_id2|industry_id2' => 'number',
        'template_id_short|template_id_short' => 'length:0,50',
        'template_id|template_id' => 'length:0,50',
        'template_message_content|template_message_content' => 'length:0,255',
        'account_message_content|account_message_content' => 'length:0,255',
        'menuid|menuid'=>'length:0,20',
        'kf_account|kf_account'=>'length:0,50',
        'nickname|nickname'=>'length:0,20',
        'password|password'=>'length:0,30',
        'redirect_uri|redirect_uri'=>'length:0,255',
        'scope|scope'=>'in:snsapi_base,snsapi_userinfo',
        'lang|lang'=>'length:0,10',
        'tag|tag'=>'length:0,20',
        'tagid|tagid'=>'number',
        'next_openid|next_openid'=>'length:0,50',
        'is_safe|is_safe'=>'length:0,5',
        'signature|signature'=>'length:0,100',
        'action|action'=>'in:long2short',
        'long_url|long_url'=>'length:0,255',
        'scene|scene' => 'length:0,50',
        'data|data' => 'length:0,255',
        'mch_id|mch_id' => 'length:0,32',
        'device_info|device_info' => 'length:0,32',
        'nonce_str|nonce_str' => 'length:0,32',
        'sign|sign' => 'length:0,32',
        'sign_type|sign_type' => 'length:0,32',
        'body|body' => 'length:0,128',
        'detail|detail' => 'length:0,6000',
        'attach|attach' => 'length:0,127',
        'out_trade_no|out_trade_no' => 'length:0,32',
        'total_fee|total_fee' => 'number',
        'fee_type|fee_type' => 'length:0,16',
        'spbill_create_ip|spbill_create_ip' => 'length:0,64',
        'goods_tag|goods_tag' => 'length:0,32',
        'limit_pay|limit_pay' => 'length:0,32',
        'time_start|time_start' => 'length:0,14',
        'time_expire|time_expire' => 'length:0,14',
        'receipt|receipt' => 'length:0,8',
        'auth_code|auth_code' => 'length:0,128',
        'scene_info|scene_info' => 'array',
        'notify_url|notify_url' => 'length:0,255',
        'trade_type|trade_type' => 'length:0,16',
        'product_id|product_id' => 'length:0,32',
        'transaction_id|transaction_id' => 'length:0,32',
        'mch_appid|mch_appid' => 'length:0,50',
        'mchid|mchid' => 'length:0,32',
        'partner_trade_no|partner_trade_no' => 'length:0,32',
        'check_name|check_name' => 'in:NO_CHECK,FORCE_CHECK',
        'desc|desc' => 'length:0,100',
        'amount|amount' => 'number',
        're_user_name|re_user_name' => 'length:0,50',
        'encrypt_type|encrypt_type'=>'length:0,20',
        'component_appid|component_appid'=>'length:0,20',
        'component_appsecret|component_appsecret'=>'length:0,100',
        'component_verify_ticket|component_verify_ticket'=>'length:0,100',
        'component_access_token|component_access_token'=>'length:0,255',
        'pre_auth_code|pre_auth_code'=>'length:0,255',
        'auth_type|auth_type'=>'in:1,2,3',
        'authorization_code|authorization_code'=>'length:0,255',
        'authorizer_appid|authorizer_appid'=>'length:0,20',
        'authorizer_refresh_token|authorizer_refresh_token'=>'length:0,255',
        'option_name|option_name'=>'length:0,50',
        'option_value|option_value'=>'length:0,50',
        'offset|offset'=>'number',
        'count|count'=>'number',
        'state|state'=>'length:0,128',
        'code|code'=>'length:0,128',
        'action_name|action_name'=>'in:QR_SCENE,QR_STR_SCENE,QR_LIMIT_SCENE,QR_LIMIT_STR_SCENE',
        'refresh_token|refresh_token' => 'length:0,100',
    ];

    public $scene = [

    ];
}